In [1]:
import scipy.io
import csv
import pymysql
import pandas as pd
from sqlalchemy import create_engine

# db 연결을 얻어오는 클래스
class DBConnector:
    
#   private member variable

    __host = '127.0.0.1'
    __user = 'root'
    __password = '1234'
    __db = 'capstone'
    __charset = 'utf8'
    
    def __init__(self) :
        
        print('init DBConnector')
        
    def getDBConnection(self) :
        
        cursorclass = pymysql.cursors.DictCursor
        
        conn = pymysql.connect(host=self.__host, user=self.__user, password=self.__password,

                       db=self.__db, charset=self.__charset,cursorclass=cursorclass)
        
        return conn

    def getDBEngine(self) :
        
        engine = create_engine("mysql+pymysql://{user}:{pw}@localhost/{db}"
                       .format(user=self.__user,
                               pw=self.__password,
                               db=self.__db))
        
        return engine
    

# table로 부터 데이터를 얻어오는 클래스
class DataGetter:
    
#   DBConnector를 인수로 전달

    def __init__(self,connector) :
        
        self.connector = connector

    def selectData(self,start,end) :
        
        conn = self.connector.getDBConnection()
          
        curs = conn.cursor()
        
        query = "SELECT * FROM test_data WHERE date >= '" +  start +  "' AND date < '" + end + "'"
        
        curs.execute(query)
        
        result = curs.fetchall()
        
        data = pd.DataFrame(result).set_index(['date'])

        return data

# mysql 스키마를 생성한 후 db에 스키마 이름이 들어가야 됨
# conn = pymysql.connect(host='127.0.0.1', user='root', password='1234',

#                        db='capstone', charset='utf8',cursorclass=pymysql.cursors.DictCursor)

# conn.commit()

# # table을 dataframe으로 저장
# curs = conn.cursor()
# curs.execute("SELECT * FROM test_data WHERE date >= '2015-01-01' AND date < '2016-12-31'")

# result = curs.fetchall()

# df = pd.DataFrame(result)
# df
    
# # create table
# # mycursor.execute("CREATE TABLE customers(name VARCHAR(255), address VARCHAR(255))")

# # read csv Data to dataframe
# data= pd.read_excel('sejong_power_consumption_per_hour_train_data.xlsx', index=True,index_col='date',sheet_name ="Sheet1" )
# data

# # create sqlalchemy engine
# engine = create_engine("mysql+pymysql://{user}:{pw}@localhost/{db}"
#                        .format(user="root",
#                                pw="1234",
#                                db="capstone"))

# # read csv Data to dataframe
# data= pd.read_excel('sejong_power_consumption_per_hour_train_data.xlsx', index=True,index_col='date',sheet_name ="Sheet1" )

# # save dataframe to table
# data.to_sql('test_data', con = engine, if_exists = 'append', chunksize = 1000)

# # read table to datafram
# conn = engine.connect()
# data = pd.read_sql_table('test_data',conn,index_col='date')
# data


# connector = DBConnector()
# connector


# # In[3]:


# conn = connector.getDBConnection()
# conn


# # In[8]:


# getter = DataGetter(conn)
# df = getter.selectData('2015-01-01','2020-01-01')


# # In[9]:


# df


# # In[93]:


# conn = test2.connect()
# data = pd.read_sql_table('test_data',conn,index_col='date')
# data


# # In[ ]:


# connector = DB

In [4]:
# connector = DBConnector()
getter = DataGetter(DBConnector())
df = getter.selectData('2015-01-01','2020-01-01')

df

init DBConnector

,consumption,humidity,isHoliday,temperature,weekday,windSpeed
date,,,,,,
2015-01-01 00:00:00,1638.36,38.00,1.00,-8.30,3.00,4.00
2015-01-01 01:00:00,1603.80,37.00,1.00,-8.20,3.00,4.80
2015-01-01 02:00:00,1578.24,34.00,1.00,-7.00,3.00,2.60
2015-01-01 03:00:00,1561.68,32.00,1.00,-6.20,3.00,2.80
2015-01-01 04:00:00,1550.52,32.00,1.00,-5.00,3.00,2.20
2015-01-01 05:00:00,1564.20,32.00,1.00,-5.30,3.00,4.10
2015-01-01 06:00:00,1562.40,33.00,1.00,-4.70,3.00,3.50
2015-01-01 07:00:00,1631.16,34.00,1.00,-4.60,3.00,3.00
2015-01-01 08:00:00,1759.68,37.00,1.00,-4.90,3.00,3.30
2015-01-01 09:00:00,1854.72,40.00,1.00,-5.00,3.00,2.80
2015-01-01 10:00:00,1884.96,42.00,1.00,-5.50,3.00,3.50
2015-01-01 11:00:00,1894.68,44.00,1.00,-6.20,3.00,3.70
2015-01-01 12:00:00,1915.92,45.00,1.00,-6.50,3.00,1.60
2015-01-01 13:00:00,1968.84,46.00,1.00,-6.60,3.00,2.60
2015-01-01 14:00:00,2011.68,47.00,1.00,-6.90,3.00,2.80
2015-01-01 15:00:00,1914.84,48.00,1.00,-7.10,3.00,2.40
2015-01-01 16:00:00,1932.48,50.00,1.00,-7.00,3.00,2.50
2015-01-01 17:00:00,1898.64,50.00,1.00,-6.30,3.00,0.90
2015-01-01 18:00:00,1960.92,53.00,1.00,-6.10,3.00,0.80
2015-01-01 19:00:00,1942.56,52.00,1.00,-6.60,3.00,1.30
2015-01-01 20:00:00,1911.24,53.00,1.00,-6.70,3.00,0.90
2015-01-01 21:00:00,1883.52,52.00,1.00,-6.40,3.00,2.40
2015-01-01 22:00:00,1828.44,54.00,1.00,-6.20,3.00,2.20
2015-01-01 23:00:00,1754.64,57.00,1.00,-7.20,3.00,1.30
2015-01-02 00:00:00,1735.56,57.00,0.00,-6.30,4.00,1.00
2015-01-02 01:00:00,1681.56,51.00,0.00,-5.20,4.00,1.30
2015-01-02 02:00:00,1668.24,39.00,0.00,-4.20,4.00,2.60
2015-01-02 03:00:00,1634.04,36.00,0.00,-3.60,4.00,4.40
2015-01-02 04:00:00,1639.80,34.00,0.00,-2.80,4.00,3.20
2015-01-02 05:00:00,1706.76,30.00,0.00,-2.20,4.00,3.10
...,...,...,...,...,...,...
2019-12-30 18:00:00,2822.88,54.00,0.00,-8.10,0.00,2.00
2019-12-30 19:00:00,2624.64,50.00,0.00,-8.50,0.00,1.60
2019-12-30 20:00:00,2460.48,51.00,0.00,-8.90,0.00,1.80
2019-12-30 21:00:00,2334.72,47.00,0.00,-9.10,0.00,3.30
2019-12-30 22:00:00,2160.00,46.00,0.00,-9.20,0.00,2.00
2019-12-30 23:00:00,2002.08,41.00,0.00,-8.90,0.00,1.90
2019-12-31 00:00:00,1976.16,36.00,0.00,-8.20,1.00,2.00
2019-12-31 01:00:00,1969.92,33.00,0.00,-7.20,1.00,2.10
2019-12-31 02:00:00,1905.60,32.00,0.00,-6.40,1.00,2.00
2019-12-31 03:00:00,1915.68,31.00,0.00,-5.30,1.00,2.30
2019-12-31 04:00:00,1965.60,32.00,0.00,-4.30,1.00,2.90
2019-12-31 05:00:00,1975.20,32.00,0.00,-4.30,1.00,2.20
2019-12-31 06:00:00,2208.00,30.00,0.00,-4.30,1.00,2.60
2019-12-31 07:00:00,2393.28,34.00,0.00,-4.80,1.00,2.70
2019-12-31 08:00:00,2621.28,34.00,0.00,-5.00,1.00,2.30
2019-12-31 09:00:00,3208.32,36.00,0.00,-5.30,1.00,1.80
2019-12-31 10:00:00,3434.88,42.00,0.00,-5.30,1.00,1.40
2019-12-31 11:00:00,3533.76,37.00,0.00,-5.60,1.00,1.70
2019-12-31 12:00:00,3456.48,37.00,0.00,-6.10,1.00,0.50
2019-12-31 13:00:00,3459.36,45.00,0.00,-5.40,1.00,1.10
2019-12-31 14:00:00,3477.60,44.00,0.00,-5.10,1.00,1.30
2019-12-31 15:00:00,3446.40,44.00,0.00,-4.80,1.00,0.90
2019-12-31 16:00:00,3286.08,47.00,0.00,-4.50,1.00,0.80
2019-12-31 17:00:00,2992.32,53.00,0.00,-4.60,1.00,1.30
2019-12-31 18:00:00,2775.84,61.00,0.00,-4.70,1.00,1.20
2019-12-31 19:00:00,2527.20,60.00,0.00,-4.50,1.00,1.50
2019-12-31 20:00:00,2456.16,62.00,0.00,-4.30,1.00,0.50
2019-12-31 21:00:00,2309.76,66.00,0.00,-4.00,1.00,0.90
2019-12-31 22:00:00,2064.96,70.00,0.00,-4.00,1.00,0.60
2019-12-31 23:00:00,1995.36,78.00,0.00,-4.10,1.00,0.90