In [1]:
import plotly
import plotly.graph_objs as graph_objs

import pandas as pd
import numpy as np
import json

import os
import sys

# sys.path.append(os.path.dirname(os.path.abspath(os.path.dirname('__AccessDB.py__'))))
sys.path.append("..")

from AccessDB.AccessDB import *

# class Visualize:
    
#     # plot object getter
#     # type : 어떤 그래프를 그려야 되는지
#     # startDate : 시작 일자
#     # endDate : 종료 일자
#     def getPlot(self,type,startDate,endDate) :

#     # table object getter
#     def getTable(self,type,startDate,endDate) :
        
        
# class Table :
    
#     def createTableData(self,startDate,endDate) : 
    

# create plot object and return 


class Plot :
        
    
    def __init__(self) :
        print("init Plot Instance")
    
    # 1. 전력 사용량 패턴 분석 > 전력 사용량 분석 plot
    # self를 인자로 받으면 객체를 만들고 생성해야함!
    # 없으면 객체 생성 안하고 사용 가능
    
    def createBarLinePlot(self,startDate,endDate) : 

        connector = DBConnector()

        dataGetter = DataGetter(connector)

        data = dataGetter.selectData('2015-01-01','2015-01-02')

        print(data)

        graph = [
            go.Bar(x=data.index, y=data['consumption'])
        ]

        graphJSON = json.dumps(graph, cls=plotly.utils.PlotlyJSONEncoder)

        return graphJSON
        
        return data

#     # 2. 전력 사용량 패턴 분석 > 예측 전력 사용량 비교 plot
#     def createCompareBarPlot(self,startDate,endDate) :
    
#     # 3. 전력 사용량 패턴 분석 > 입력변수 데이터 통계 plot
#     def createLinePlot(self,startDate,endDate) :

#     # 4. CCHP 스케줄링 > 전력 사용량 예측 Plot
#     def createBarPlot(self,startDate,endDate) : 

#     # 5. CCHP 스케줄링 > CCHP 스케줄링 Plot
#     def createDoubleBarPlot(self,startDate,endDate) : 
    
#     # 6. CCHP 스케줄링 > CCHP 운영 시간표
#     def createPiePlot(self,startDate,endDate) : 
    
#     # 7. 경제성 분석 > 경제성 분석 : BarPlot, PieChart

#     # 8. 경제성 분석 > 다른 요금제와 비교
#     def createCompareLinePlot(self) :

In [2]:
plot = Plot()
plot

init Plot Instance

In [3]:
plot.createBarLinePlot('2015-01-01','2015-01-02')

init DBConnector

,consumption,humidity,isHoliday,temperature,weekday,windSpeed
date,,,,,,
2015-01-01 00:00:00,1638.36,38.00,1.00,-8.30,3.00,4.00
2015-01-01 01:00:00,1603.80,37.00,1.00,-8.20,3.00,4.80
2015-01-01 02:00:00,1578.24,34.00,1.00,-7.00,3.00,2.60
2015-01-01 03:00:00,1561.68,32.00,1.00,-6.20,3.00,2.80
2015-01-01 04:00:00,1550.52,32.00,1.00,-5.00,3.00,2.20
2015-01-01 05:00:00,1564.20,32.00,1.00,-5.30,3.00,4.10
2015-01-01 06:00:00,1562.40,33.00,1.00,-4.70,3.00,3.50
2015-01-01 07:00:00,1631.16,34.00,1.00,-4.60,3.00,3.00
2015-01-01 08:00:00,1759.68,37.00,1.00,-4.90,3.00,3.30
2015-01-01 09:00:00,1854.72,40.00,1.00,-5.00,3.00,2.80
2015-01-01 10:00:00,1884.96,42.00,1.00,-5.50,3.00,3.50
2015-01-01 11:00:00,1894.68,44.00,1.00,-6.20,3.00,3.70
2015-01-01 12:00:00,1915.92,45.00,1.00,-6.50,3.00,1.60
2015-01-01 13:00:00,1968.84,46.00,1.00,-6.60,3.00,2.60
2015-01-01 14:00:00,2011.68,47.00,1.00,-6.90,3.00,2.80
2015-01-01 15:00:00,1914.84,48.00,1.00,-7.10,3.00,2.40
2015-01-01 16:00:00,1932.48,50.00,1.00,-7.00,3.00,2.50
2015-01-01 17:00:00,1898.64,50.00,1.00,-6.30,3.00,0.90
2015-01-01 18:00:00,1960.92,53.00,1.00,-6.10,3.00,0.80
2015-01-01 19:00:00,1942.56,52.00,1.00,-6.60,3.00,1.30
2015-01-01 20:00:00,1911.24,53.00,1.00,-6.70,3.00,0.90
2015-01-01 21:00:00,1883.52,52.00,1.00,-6.40,3.00,2.40
2015-01-01 22:00:00,1828.44,54.00,1.00,-6.20,3.00,2.20
2015-01-01 23:00:00,1754.64,57.00,1.00,-7.20,3.00,1.30

In [ ]:
connector = AccessDB
connector.DBConnector()

In [ ]:
dir()

In [ ]:
connector = DBConnector()
dataGetter = DataGetter(connector)

In [3]:
dataGetter.connector

NameError: name 'dataGetter' is not defined

In [14]:
connector = DBConnector()
connector

In [17]:
conn = connector.getDBConnection
conn

In [23]:
dataGetter = DataGetter(connector)
dataGetter.selectData('2015-01-01','2015-01-02')

TypeError: getDBConnection() takes 0 positional arguments but 1 was given

In [8]:
import plotly
import plotly.graph_objs as go
import numpy as np
import pandas as pd
import json

In [10]:
graphJSON

'[{"x": [0.0, 0.02564102564102564, 0.05128205128205128, 0.07692307692307693, 0.10256410256410256, 0.1282051282051282, 0.15384615384615385, 0.1794871794871795, 0.20512820512820512, 0.23076923076923075, 0.2564102564102564, 0.28205128205128205, 0.3076923076923077, 0.3333333333333333, 0.358974358974359, 0.3846153846153846, 0.41025641025641024, 0.4358974358974359, 0.4615384615384615, 0.48717948717948717, 0.5128205128205128, 0.5384615384615384, 0.5641025641025641, 0.5897435897435898, 0.6153846153846154, 0.641025641025641, 0.6666666666666666, 0.6923076923076923, 0.717948717948718, 0.7435897435897436, 0.7692307692307692, 0.7948717948717948, 0.8205128205128205, 0.8461538461538461, 0.8717948717948718, 0.8974358974358974, 0.923076923076923, 0.9487179487179487, 0.9743589743589743, 1.0], "y": [1.4867457362169438, -0.964736661144342, 1.8778048635481588, -0.40470781046840143, 0.1917172143358663, -1.2986778167335367, 0.3986877220576646, -2.2964784198292434, 1.2042127046844606, -0.19907659634405123, -1.8753969424910624, -0.48449173711982485, -0.7757828426930303, -0.08684608314938282, -0.2885923908442752, -0.25891512814055656, -0.769905707476707, -0.4758084186550224, 0.8144377798413049, -0.15216419736585607, 1.2427370889493214, 0.33649392265960953, -0.6850369600766134, -0.7700485640577328, -0.9389915551177229, -0.5544851878235046, -0.5493535747219405, -0.2928796070800315, 0.7220000640366957, 0.5700153698646333, 0.6113898239815134, -0.7381891767142502, -1.193021412889898, -1.2608142859470504, -0.5540651199734159, -1.2290659998592777, 0.692111296971467, 0.743353036752157, 1.4029541409602724, -1.7994089673886833], "type": "bar"}]'